### PR TITLE
RFC: Add support for BDEPEND and - internally - split up build_depend(encies) into build_depend(encies)_target and build_depend(encies)_host.

### PR DESCRIPTION
**Pull request by Ionic**
Related to #6

Note that this implementation currently doesn't check the EAPI
correctly or at all, so even EAPIs < 6 get the new BDEPEND support.

The new test case will *fail* due to this (and also doesn't check the
eapi in a good fashion - it shouldn't be using a string comparison).

***

For now, let's make this an RFC. I'd like to have some feedback.

The implementation is rather simple, but very noisy (diff-wise). It *seems* to work as far as I can tell by testing with one specific package, but I'm not sure if it's really working correctly.

One thing that I definitely didn't implement is architecture checking. The build dependencies are just merged into one list at some point and interpreted as such by the resolver.

Also, EAPI checking isn't correctly implemented because... I have no idea how to do so. EAPI 7 is the first one to add a new global variable, as far as I remember, so there is no preceding example of how to implement something like this correctly.
I could have set `..._depend_host =` in the EAPI 0 definition and only to `... = BDEPEND` the EAPI 7 definition, but I'm not sure if that's the correct route to go. The eapi check in my new test case is based on a string comparison which looks so very wrong, but I have no idea how to actually get a numerical EAPI representation. Even worse, there may be no such way, because EAPIs need not be entirely (or at all) numerical, as exemplified by "exheres-0" or "paludis-1". I guess I should have used the `eapi()->supported()->...` API there instead - but that would require to have a feature that can be set to supported or unsupported in the first place.

### CODE REVIEW

**Comment by Ionic** [comment]
I reworked this a good bit, but it's still not yet merge-ready.


> EAPI 7 is the first one to add a new global variable

Turns out I was wrong - EAPI 4 introduced `REQUIRED_USE` for instance, which I was able to use as a reference.

I've changed the patch to not support `BDEPEND` for pre-7 EAPI's (I hope).

> Could you give a hint which change you mean? Maybe I miss something or depend_bdepend test is not included ...

It wasn't, oops. Rectified.


`cave` seems to crash currently in the EAPI-7-bdepend test case, will have to investigate this.


Also added a note on the API breakage bit, which means that we'd have to bump the version number, which... sucks.

**Comment by MageSlayer** [comment]
> I've changed the patch to not support `BDEPEND` for pre-7 EAPI's (I hope).

It's nice that you've made a test for that.

I guess, it's better to change copyright in depend_bdepend_TEST.cc
Ciaran won't be happy when someone contacts him about any issues :)

Also, please avoid squashing commits and force-pushing. This commit is already too large...

**Comment by Ionic** [comment]
> It's nice that you've made a test for that.

Yeah, though I'm not sure whether it should be an independent test or rather part of the EAPI 7 test suite. On the other hand, we'd also have to test previous EAPIs which don't support that feature, so it's probably okay that way...


> I guess, it's better to change copyright in depend_bdepend_TEST.cc
> Ciaran won't be happy when someone contacts him about any issues :)

Rather add a new statement, probably. My rationale for not changing the copyright was the test case essentially being only a slightly modified copy of the rdepend test.


> Also, please avoid squashing commits. This commit is already too large...

I know, but the problem with that is that most changes are really one functional unit. I can and should have split out the test case additions easily, maybe also the EAPI definition updates, but other than that the core changes really are one big change.


> and force-pushing

Makes reviewing changes harder, yeah, but PRs and feature branches are typically often rebased. Maybe I should only do so at the end and add changes incrementally first, then fix it up/rebase it before the actual merge.


I haven't had time for looking into the test case crashing. Last time I tried I gave up unnerved, since the backtrace wasn't helpful at all and gdb doesn't even provide meaningful introspection for this stuff. I'll have to fix it, though, since there definitely is some issue.

**Comment by Ionic** [comment]
Did some rebasing, splitting stuff up and finally managed to fix the failing test case. It really boiled down to a typo in the setup script and not modifying `ebuild.bash` correctly, but it was difficult to diagnose.

The test case's support setup script contained an error which I fixed without an additional commit (left RDEPEND in place of BDEPEND in one place, whoops).

Everything else was done on top of the other already available commits.

As always, don't merge, it's still not done. I'm seeing these test case failures:

The following tests FAILED:
         89 - e_repository_5 (Failed)
         90 - e_repository_6 (Failed)
         93 - e_repository_exheres_0 (Failed)

Will need to further investigate those. Not sure if they are regressions or have been broken for quite some time - will also run the test suite without this PR's code added.

**Comment by Ionic** [comment]
Okay, these test failures come up even without any of the commits on this branch (but all the others on the eapi7 branch).

We probably should look into them, but as far as I can tell they are not relevant for this PR.

Now, with that sorted... I'm pretty happy with the way this PR looks like right now. It'll need a final squash run to merge the last two marked commits into previous ones since they only fix up stuff that was previously broken, but it does what we need (to some degree).

As already said, it's not a full solution to the problem at hand - there are no architecture checks. That will be needed to be implemented as well at some point, but it's arguably more important to fetch all dependencies and use them (overly) correctly.

**Comment by MageSlayer** [comment]
Looks good to me.

**Comment by Ionic** [comment]
Okay, gave it one last rebase.

Before actually merging this, there's one open point I forgot about: what shall we do about the API break? Bindings now need to use the new names, so that's breaking API.

We probably should version-bump paludis, but is that a good idea? After all, the fork's version number would diverge from the original repository and that sounds a bit weird.

**Comment by MageSlayer** [comment]
Well. I would like to avoid changing version for now.
API break is for scripts only, right? I think, it's enough to document it in readme and be done with it.

**Comment by Ionic** [comment]
Yep, only for scripts that use said bindings.

Done, added some documentation for this.

**Comment by MageSlayer** [comment]
Thanks a lot for your effort.
I'll try to give it another review and merge.

**Pull request merged**
