### PR TITLE
Rebase eapi7 branch against updated master branch

### PR DESCRIPTION
**Pull request by Ionic**
This rebases the eapi7 branch against the newly updated master branch, without any changes (apart from what upstream brought in during the last four years).

### CODE REVIEW

**Comment by MageSlayer** [comment]
I cannot build this branch.
It fails with:
```
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:110:25: error: expected constructor, destructor, or type conversion before '(' token
  110 | INSTANTIATE_TEST_SUITE_P(GeneratorTest, GeneratorTestCaseBase, testing::Values(
      |                         ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:117:39: error: expected unqualified-id before ',' token
  117 |                 "cat/c-3:0::repo2" ) },
      |                                       ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:119:21: error: expected constructor, destructor, or type conversion before '{' token
  119 |             TestInfo{ std::make_shared<generator::Matches>(
      |                     ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:124:38: error: expected unqualified-id before ',' token
  124 |                 "cat/a-2:0::repo2") },
      |                                      ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:126:21: error: expected constructor, destructor, or type conversion before '{' token
  126 |             TestInfo{ std::make_shared<generator::Matches>(
      |                     ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:131:38: error: expected unqualified-id before ',' token
  131 |                 "cat/a-2:0::repo2") },
      |                                      ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:133:21: error: expected constructor, destructor, or type conversion before '{' token
  133 |             TestInfo{ std::make_shared<generator::Matches>(
      |                     ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:140:38: error: expected unqualified-id before ',' token
  140 |                 "cat/c-3:0::repo2") },
      |                                      ^
/home/denis/projects/c/paludis-gentoo-patches/paludis/generator_TEST.cc:142:21: error: expected constructor, destructor, or type conversion before '{' token
  142 |             TestInfo{ std::make_shared<generator::Matches>(
      |                     ^
...
```
... when trying 
```
$ cmake . 
$ make -j8
```

**Comment by Ionic** [comment]
Thanks, I'll look into it.

**Comment by Ionic** [comment]
Are you on `=dev-cpp/gtest-1.11.0` by any chance? I'm still on `1.10.0_p20200702`, which might behave differently.

I'll update and see if it fails for me as well.

**Comment by MageSlayer** [comment]
Ok. I see now.
I had old gtest-1.8.0-r1.
I've upgraded to 1.10.0_p20200702 and now it builds fine.

**Comment by Ionic** [comment]
Exherbo upstream pushed a fix for that last year. Gtest deprecated the old function quite hastily. Good that it works. :)

**Comment by MageSlayer** [comment]
Another issue:
```
$ cmake . -DENABLE_PYTHON=yes
```


```
...
-- Found Python: /usr/bin/python2.7 (found suitable exact version "2.7.18") found components: Interpreter Development Development.Module Development.Embed 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: python) (found suitable version "1.75.0",
  minimum required is "1.75.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)
  CMakeLists.txt:331 (find_package)
```

**Comment by Ionic** [comment]
`boost` does not support python 2.7 longer.

Additionally pass `-DPYTHON_VERSION=X.Y` (which `X.Y` matching what boost was built with, e.g., `3.9`) and it should work.

In ebuild-parlance, it would be `-DPYTHON_VERSION=${EPYTHON#python}`.

**Comment by MageSlayer** [comment]
Upgrading to boost-1.76.0 seems to fix the issue.

I guess it's better to drop 2.7 support altogether.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6b81fc08d..9fec8265c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -50,9 +50,7 @@ endif()
 set(PALUDIS_VIM_INSTALL_DIR "${CMAKE_INSTALL_FULL_DATADIR}/vim/vimfiles" CACHE PATH
     "vim installation directory")
 
-set(PYTHON_SUPPORTED_VERSIONS 2.7 3.6 3.7 3.8 3.9 3.10)
-set(PYTHON_VERSION "2.7" CACHE STRING
-  "Python version (${PYTHON_SUPPORTED_VERSIONS}) (requires corresponding Boost.Python as well)")
+set(PYTHON_SUPPORTED_VERSIONS 3.7 3.8 3.9 3.10)
 
 set(RUBY_SUPPORTED_VERSIONS 2.6 2.7 3.0)
 set(RUBY_VERSION "2.7" CACHE STRING "Ruby Version (${RUBY_SUPPORTED_VERSIONS})")
```

However it causes another problem - seems like dev-python/sphinx cannot be emerged due to :
```
!   dev-python/imagesize
    Reasons: dev-python/sphinx-3.5.4:0::gentoo
    Unsuitable candidates:
      * Found no packages for resolvent dev-python/imagesize:(unknown)::(install_to_slash)
!   dev-python/pytz
    Reasons: dev-python/Babel-2.9.1:0::gentoo
    Unsuitable candidates:
      * Found no packages for resolvent dev-python/pytz:(unknown)::(install_to_slash)
```

**Comment by Ionic** [comment]
Yeah, Python 2.7 support should be fully dropped, since it's dead upstream anyway.

The whole EAPI=8 stuff is a bit inconvenient, I know. :/

Back when I had no complete implementation, I typically downgraded packages carefully to EAPI=7 (including their metadata cache) by utilizing the checklist and making sure that not EAPI=8 features were used (or rewrote it so that they weren't), but this gets tiresome when a lot of packages are involved, especially in the case of sphinx...

**Comment by Ionic** [comment]
Merged in changes from PR#41, please don't merge this PR before the other.

**Comment by Ionic** [comment]
Updated to the 2022 version of my rebased master branch. I also dropped the changes from #41 for now, will merge that in individually, since I also have a myriad of other changes after that.

**Comment by Ionic** [comment]
Needs a bit more love, so converted to draft for now. Will undraft once the rough edges are out.

**Comment by Ionic** [comment]
Done. Everything looks fine now.

**Comment by thesamesam** [comment]
Could you rebase this again so the github view is nicer?

**Comment by Ionic** [comment]
Yep, but still a valid point, I'll rebase this branch once #37 is properly merged.

**Comment by Ionic** [comment]
Rebased, merging.

**Pull request merged**
