### PR TITLE
bugfix: fix loadsaveenv

### PR DESCRIPTION
**Pull request by Ionic**
So far, paludis used "set" to dump all shell and environment variables
out to a file (c.f., "environment.bz2") and then a small utility called
"print_exports", which issued "export" calls for exported environment
variables.

It also had a way to rewrite environment dump files that have been
created using "declare -p" into its own expected form.

This worked more or less fine, but is considered a legacy environment
dump form. Portage and pkgcore switched to the "declare -p" form a long
time ago and recently, not using it started causing trouble.

For instance, the go-module eclass started using bash associative
arrays.

These are a bit weird in that they can't be created without a declare
call. By default, bash assumes normal arrays when it sees that syntax
and the only way to change that is using the "declare" or "typeset"
builtin.

Crucially, this also means that you cannot dump and reapply associative
arrays with the set builtin.

Other complex variables with additional attributes (such as integer-type
or automatic lower and uppercase conversion variables) can behave
wrongly when being used later on without applying the attributes.

Hence, we'll also switch to the more sophisticated declare/typeset tool
and let it print out variables (attributes, names, values) and later on
functions.

Additionally, avoid subshells (slow) and use compound commands instead
and correctly quote the target file.

We can now also drop the --rewrite-for-declare flag to
ebuild_safe_source, since going forward, our environment dump files will
all contain "declare" calls anyway.

For this to work correctly, we'll have to modify the variable name
detection/skip code to handle lines starting with "declare <options>"
correctly and make sure that variables are NOT set locally within the
shell function only. For the latter issue, make sure to add -g to any
declare calls when applying the dumped data.

Lastly, properly document the ebuild_safe_source function. It's
complicated and took me a lot of time to understand how it works
multiple times in a row. Better explain it in some easily understandable
textual form.

Fixes: https://github.com/MageSlayer/paludis-gentoo-patches/issues/26

---

Since we don't need the `print_exports` utility any longer, drop that.

---

Test cases all pass, building `net-misc/geoipupdate` with the pristine `go-module` eclass (that nowadays uses associative arrays) also succeeds.

### CODE REVIEW

**Comment by MageSlayer** [comment]
Thanks for the fix.
I'll merge it today, a bit later.

**Comment by MageSlayer** [comment]
Nice commenting!
This gives a lot of value. Keep on doing that :)

**Comment by Ionic** [comment]
Yeah... I actually had to figure out what the function does twice from scratch in three months. Got tired of that and decided to actually write it up in comments because it really isn't all that obvious. :)

**Comment by MageSlayer** [comment]
Hm, now I am getting something like:
```
rm /var/tmp/paludis/environment-net-dns-c-ares-1.16.1-27164
/var/tmp/paludis/environment-net-dns-c-ares-1.16.1-27164: line 716: print_exports: command not found
```
when upgrading packages.

**Comment by Ionic** [comment]
Oh, we'll have to back out the second commit them and keep it around! Just revert it please. No further changes needed.

**Comment by Ionic** [comment]
I totally forgot that older environment dump files will still contain `print_exports`. We can't easily remove the binary, even if we stopped using it. Legacy it is now. :/

**Comment by MageSlayer** [comment]
Aha. I reverted that commit.
Looks good. Thanks for quick response.

**Pull request merged**
