### PR TITLE
Rebase master branch against newly updated upstream branch

### PR DESCRIPTION
**Pull request by Ionic**
Pulls in a lot of changes from upstream.

The merge commit also removes some of the more questionable Python changes in the top-level `CMakeLists.txt`. It seems to work fine that way with my ebuild, c.f. https://git.ionic.de/gentoo-overlay.git/blob/HEAD:/sys-apps/paludis/paludis-3.0.0_pre20210616.ebuild

Other than that, no real changes and quite a few bug fixes from upstream.

### CODE REVIEW

**Comment by Ionic** [comment]
Admittedly, the PRs are getting a bit unwieldy due to the internal dependencies, but the general course of action is:
  1. #37 (this one)
  2. #41 for a general bugfix that affects EAPI=0 and higher
  3. #38 for the EAPI=7 branch rebase against the current master, including the fix above
  4. #39 for python and ruby test fixes on the EAPI=7 branch.

I'll undraft PRs (and rebase them, for cleaner looks) as prerequisites get merged.

**Comment by Ionic** [comment]
Updated against current/updated upstream branch. Update done via merge.

The only relevant change is that upstream dropped checking for the Linux kernel major version number, which makes Denis's patch redundant.

This will work until we reach Linux version 10.

**Comment by Ionic** [comment]
Added another merge commit for the newly updated upstream branch. That should make it synchronized. It's a bit ugly, because there's now 3 merge commits at the top of the history, but it's probably the right thing to do. I could try to rebase it, but that doesn't work nicely with merges.

**Comment by Ionic** [comment]
... and actually redid the whole merge stuff to get rid one merge commit. That looks a lot cleaner now. :)

`git reflog` is one of the most useful features.

**Comment by thesamesam** [comment]
It really is magical.

**Pull request merged**
